<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Exception Handling</title>
<link rel=STYLESHEET href="/~rhowell/style.css">

</head>

<body>
<div class="NAVBAR">
<a
      href="/~rhowell/DataStructures/redirect/advanced-text-file-io">Next:
      Advanced Text File I/O
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
      href="/~rhowell/DataStructures/redirect/simple-text-file-io">Previous:
      Simple Text File I/O
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
      href="/~rhowell/DataStructures/redirect/io">Up: Input/Output
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
      href="/~rhowell/DataStructures/">Top</a>
</div>

<h1>Exception Handling</h1>

As was mentioned in <a
      href="/~rhowell/DataStructures/redirect/simple-text-file-io">the
      previous section</a>, various problems can occur when doing file
      I/O.  Some of these problems include:
<ul>
<li> Trying to write to a read-only file. </li>
<li> Trying to access a file that is locked by another process. </li>
<li> Accessing an external drive that becomes disconnected. </li>
</ul>
Note that some of these issues are beyond the programmer's control,
    while others may be tedious for the programmer to check (file
    dialogs, however, can be quite helpful in avoiding some of these
    issues, as they can reject improper selections by the user).  When
    one of these problems prevents an I/O operation from completing
    successfully, an exception is thrown.  This section discusses how
    to handle such exceptions gracefully, without terminating the
    program.
<p>
The mechanism used to handle exceptions is the <b>try</b>-<b>catch</b>
      construct.  In its simplest form, it looks like:
</p>
<pre>
try
{

    // Block of code that might throw an exception

}
catch
{

    // Code to handle the exception

}
</pre>
If we are concerned about exceptions thrown while doing I/O, we would
    include the I/O and anything dependent on it within the
    <b>try</b>-block.  If at any point within this block an exception
    is thrown, control immediately jumps to the <b>catch</b>-block.
    Here, we would place code to handle the exception - for example,
    displaying a message to the user.
<p>
Suppose, for example, that we want to count the number of upper-case
      letters in a file whose name is in the <b>string</b> referenced
      by <tt>fileName</tt>.  We could use the following code:
</p>
<pre>
try
{
    string contents = File.ReadAllText(fileName);
    int count = 0;
    foreach (char c in contents)
    {
        if (Char.IsUpper(c))
        {
            count++;
        }
    }
    MessageBox.Show("The file contains " + count + " upper-case letters.");
}
catch
{
    MessageBox.Show("An exception occurred.");
}
</pre>
(See the section, "<a
      href="/~rhowell/DataStructures/redirect/foreach">The foreach
      Statement</a>" for an explanation of <b>foreach</b> loops.  The
      <a
      href="http://msdn.microsoft.com/en-us/library/system.char.isupper(v=vs.110).aspx"><b>Char.IsUpper</b></a>
      method returns a <b>bool</b> indicating whether the given
      <b>char</b> is an upper-case letter in some alphabet.)
<p>
Note that we include within the <b>try</b>-block all of the code that
      depends on what we want to read.  Consider what would happen,
      for example, if we tried to move the statement,
</p>
<pre>
MessageBox.Show("The file contains " + count + " upper-case letters.");
</pre>
outside the <b>try</b>-<b>catch</b>.  First, we would have a syntax
    error because the variable <tt>count</tt> is declared with the
    <b>try</b>-block, and hence cannot be used outside of it.  We
    could fix this error by declaring and initializing <tt>count</tt>
    prior to the <b>try</b> statement.  The resulting code would
    compile and run, but consider what happens if an exception is
    thrown during the reading of the file.  Control immediately jumps
    to the <b>catch</b>-block, where the message, "An exception
    occurred.", is displayed.  After that, assuming we have made these
    changes to the above code, control continues on past the
    <b>catch</b>-block to the code to display the results.  Because
    the file was not successfully read, it really doesn't make any
    sense to do this.  The code given above, however, displays a
    result only if the result is successfully computed; otherwise, the
    exception message is displayed.
<p>
In the above example, the message, "An exception occurred.", isn't
      very helpful to the user.  It gives no indication of what the
      problem is.  In order to be able to provide more information to
      the user, we need more information regarding the nature of the
      exception.  The way we do this is to use some additional code on
      the <b>catch</b> statement:
<pre>
catch (Exception ex)
</pre>
The word <b>Exception</b> above is a type.  Every exception in C# is a
    subtype of the <b>Exception</b> class.  In this form of the
    <b>catch</b> statement, we can include any subtype of
    <b>Exception</b>, including <b>Exception</b> itself, as the first
    word within the parentheses.  The second word is a new variable
    name.  One effect of this parenthesized part is to declare this
    variable to be of the given type; i.e., <tt>ex</tt> is of type
    <b>Exception</b>, and may be used within the <b>catch</b> block.
<p>
This form of the <b>catch</b> statement will catch any exception that
      can be treated as the given type.  If we use the type,
      <b>Exception</b>, as above, the <b>catch</b>-block will still
      catch any exception.  In addition, the variable defined within
      the parentheses will refer to that exception.  Thus, the
      parenthesized part of this statement behaves much like a
      parameter list, giving us access to the exception that was
      thrown.  Having the exception available to examine, we can now
      give more meaningful feedback to the user.  One rather crude way
      of doing this is to use the exception's <a
      href="http://msdn.microsoft.com/en-us/library/system.object.tostring.aspx"><b>ToString</b></a>
      method (which every object has) to convert it to a <b>string</b>
      representation, which can then be displayed to the user; for
      example,
</p>
<pre>
catch (Exception ex)
{
    MessageBox.Show(ex.ToString());
}
</pre>
Replacing the <b>catch</b>-block in the earlier example with this
      <b>catch</b>-block might result in the following message:
<p>
<img src="exception-box.jpg" alt="A picture of a dialog should appear here.">
</p>
A single <b>try</b>-block  can have more than one <b>catch</b>-block.
    In such a case, whenever an exception occurs within the
    <b>try</b>-block, control is transferred to the first
    <b>catch</b>-block that can catch that particular exception.  For
    example, we can set up the following construct:
<pre>
try
{

    // Code that may throw an exception

}
catch (DirectoryNotFoundException ex)
{

   // Code to handle a DirectoryNotFoundException

}
catch (FileNotFoundException ex)
{

    // Code to handle a FileNotFoundException

}
catch (Exception ex)
{

    // Code to handle any other exception

}
</pre>
If we don't need access to the exception itself in order to handle it,
    but only need to know what kind of exception it is, we can leave
    off the variable name in the <b>catch</b> statement.  For example,
    if we are trying to read from a file whose name is referenced by
    the <b>string</b> <tt>fileName</tt>, we might handle a
    <b>FileNotFoundException</b> as follows:
<pre>
catch (FileNotFoundException)
{
    MessageBox.Show("Could not find the file " + fileName);
}
</pre>

<p></p>
<div class="NAVBAR">
<a
      href="/~rhowell/DataStructures/redirect/advanced-text-file-io">Next:
      Advanced Text File I/O
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
      href="/~rhowell/DataStructures/redirect/simple-text-file-io">Previous:
      Simple Text File I/O
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
      href="/~rhowell/DataStructures/redirect/io">Up: Input/Output
      </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a
      href="/~rhowell/DataStructures/">Top</a>
</div>

<p>
<small>
<!-- hhmts start -->
Last modified: Tue Jun  5 03:50:07 CDT 2018
<!-- hhmts end -->
</small>
</p>
<small>
    <i> &copy; Copyright 2014, 2018, <a
    href="/~rhowell/">Rod Howell</a>. All
    rights reserved.</i> 
</small>

<p></p>

<table border=0 cellpadding=2 summary="This table is used for layout
purposes only.">
<tr>
<td align=center>
    <a href="http://validator.w3.org/check/referer"><img border="0"
        src="/~rhowell/valid-html401.gif"
        alt="Valid HTML 4.01!" height="31" width="88"></a>
</td>
<tr>
<td>
<a href="http://jigsaw.w3.org/css-validator/check/referer">
             <img border="0"
                  src="/~howell/vcss.gif" 
                  alt="Valid CSS!" height="31" width="88">
            </a>
</td>
</table>

</body>

</html>
